#!/bin/bash

docker build ${1} -t flowd -f deploy/build-flowd/Dockerfile --target container .

docker build ${1} -t healthd -f deploy/build-healthd/Dockerfile  --target container .

docker build ${1} -t catch-gateway -f deploy/build-catch-gateway/Dockerfile --target container .

docker build ${1} -t throw-gateway -f deploy/build-throw-gateway/Dockerfile --target container .

# build the exclusive-gateway. TODO: refactor exclusive gateway to be more like
# the others.
pushd gateway_containers/exclusive-gateway
docker build ${1} -t exclusive-gateway --target container -f Dockerfile .
popd

pushd gateway_containers/parallel-gateway
docker build ${1} -t parallel-gateway --target container -f Dockerfile .
popd





