#!/bin/bash

docker build -t flowd -f deploy/Dockerfile.flowd .

docker build -t healthd -f deploy/Dockerfile.healthd .

docker build -t catch-gateway -f deploy/Dockerfile.catch .

docker build -t throw-gateway -f deploy/Dockerfile.throw .

# build the exclusive-gateway. TODO: refactor exclusive gateway to be more like
# the others.
pushd gateway_containers/exclusive-gateway && make build && popd
pushd gateway_containers/parallel-gateway && make build && popd




