# Copyright Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# httpbin service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collect
---
apiVersion: v1
kind: Service
metadata:
  name: collect
  labels:
    app: collect
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: collect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collect
  template:
    metadata:
      labels:
        app: collect
    spec:
      serviceAccountName: collect
      containers:
      - image: collect
        imagePullPolicy: IfNotPresent
        name: collect
        ports:
        - containerPort: 5000
