apiVersion: v1
kind: ServiceAccount
metadata:
  name: profit
---
apiVersion: v1
kind: Service
metadata:
  name: profit
  labels:
    app: profit
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: profit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profit
  template:
    metadata:
      labels:
        app: profit
    spec:
      serviceAccountName: profit
      containers:
      - image: profit
        imagePullPolicy: IfNotPresent
        name: profit
        ports:
        - containerPort: 5000
