apiVersion: v1
kind: ServiceAccount
metadata:
  name: collect
---
apiVersion: v1
kind: Service
metadata:
  name: collect
  labels:
    app: collect
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: collect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collect
  template:
    metadata:
      labels:
        app: collect
    spec:
      serviceAccountName: collect
      containers:
      - image: collect
        imagePullPolicy: IfNotPresent
        name: collect
        ports:
        - containerPort: 5000
