name: parallel-gateway
channels:
- defaults
- rexchange
dependencies:
- python=3.7
- gunicorn=20.0.4
- gevent=1.4.0
- flask=1.1.1
- sqlalchemy=1.3.13
- pymysql=0.9.3
- flask-sqlalchemy=2.4.1
- requests=2.23.0
- flask-cors=3.0.8
- pytest-cov=2.8.1
- pytest-mock=3.1.1
- pip
- pip:
  - flask-restx==0.2.0
  - pydantic==1.6.1
  - psycopg2-binary==2.8.5
  - flask-migrate==2.5.3
  - pytest-env==0.6.2
  - marshmallow-jsonschema==0.10.0
  - marshmallow-sqlalchemy==0.23.1
  - pydantic-sqlalchemy==0.0.5
