FROM python:3.8-slim AS passthroughbase
WORKDIR /opt/rexflow
RUN apt-get update && apt-get install -y curl
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY flowlib flowlib/
COPY bpmn_containers/passthrough.py .
EXPOSE 5050/tcp

FROM passthroughbase AS test

CMD ["echo", "TODO: run quick unit tests here."]

FROM passthroughbase AS passthrough-container

CMD ["python", "-m", "passthrough"]
