apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: rexflow
  name: uibridge
---
apiVersion: v1
kind: Service
metadata:
  name: uibridge
  namespace: rexflow
  labels:
    app: uibridge
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: uibridge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uibridge
  namespace: rexflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uibridge
  template:
    metadata:
      labels:
        app: uibridge
    spec:
      serviceAccountName: uibridge
      containers:
      - image: rex-uibridge
        imagePullPolicy: IfNotPresent
        name: uibridge
        ports:
        - containerPort: 5000
        env:
        - name: ETCD_HOST
          value: rexflow-etcd.rexflow
        - name: I_AM_FLOWD
          value: "False"
        - name: REXFLOW_KAKFA_HOST
          value: my-cluster-kafka-bootstrap.kafka:9092
